### ISSUE TITLE
[Bug] Crash when dattempting to deconstruct ghosts

### ISSUE THREAD

**Issue by TDietrich99** [fgardt/factorio-rail-decon-planner#2]
When you are trying to deconstuct a mixed ghost/real railway, the map crashes

**Comment by fgardt** [comment]
thanks for the report, I'll take a look into that

**Comment by fgardt** [comment]
fixed with 8ad2920039181cbcdbcc44b1724905450e432390.

do note that unfortunately deconstruction/deletion of ghosts is not supported due to limitations.\
I could work around it but that would be very hacky and pretty complex :/
